name: Deploy to Production

on:
  workflow_dispatch:
  workflow_call: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'fcg-app-service'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa197e8ebb334ac3bfbae68c290bf3dd }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb933a47977a4a398a79ae34a965614f }}/fiap-cloud-games:${{ github.sha }}
