name: Deploy to Production

on:
  workflow_dispatch:
  workflow_call: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fgc-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3a1e27da800e4bac81e9fd8487bc644c }}
        images: '${{ secrets.DOCKER_USERNAME }}/fiap-cloud-games:${{ github.sha }}'
