name: Build and deploy container app to Azure Web App - fgc-app-service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fgc-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3a1e27da800e4bac81e9fd8487bc644c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca01781d7845440abca9cbae6582b477 }}/fiap-cloud-games:${{ github.sha }}'
