name: Deploy to Production

on:
  workflow_dispatch:
  workflow_call: 

jobs:
   deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fcg-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_412d86432813491f9c79648223221d46 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_47aea33d7bfd4809af75ae616212c483 }}/fiap-cloud-games:${{ github.sha }}'